#!/bin/bash

set -eu -o pipefail

_flatpak_id=$1
_flatpak_overrides="/tmp/.flatpak-overrides/$_flatpak_id"

if [ ! -f "$_flatpak_overrides" ]; then
	echo "ERROR: Missing tmpfs mountpoint for $_flatpak_id Flatpak overrides" >&2
	exit 1
fi

# If no path specified
if [ -z "${1+x}" ]; then
	flatpak --user run $_flatpak_id
	exit 0
fi

# Doesn't work with bind mount
#flatpak --user override "--filesystem=$(readlink -f $1)" $_flatpak_id

python3 - "$1" <<EOF
#!/usr/bin/env python3

from pathlib import Path
import sys

path = Path('${_flatpak_overrides}')
edit_notice = '# Edited automatically by my code-flatpak script'

content = path.read_text().splitlines()
for i in range(len(content)):
    if not content[i].startswith('filesystems='):
        continue
    filesystems = content[i][len('filesystems='):].split(';')
    to_insert = Path(sys.argv[1])
    if not to_insert.exists():
        print('ERROR: Path does not exist', file=sys.stderr)
        sys.exit(1)
    to_insert = str(Path(sys.argv[1]).absolute())
    if to_insert in filesystems:
        break
    filesystems.insert(2, to_insert)
    content[i] = 'filesystems=' + ';'.join(filesystems)
if content[0] != edit_notice:
    content.insert(0, edit_notice)
path.write_text('\n'.join(content))
EOF

flatpak --user run $_flatpak_id "${@:2}"
